javascript:  
  image: node:latest

  stages:
    - test

  test:
    stage: test
    script:
      - npm run tsc
      - npm run main
      - npm run lint --fix
      - npm run format
    before_script:
      - npm i --save-dev
      - npm ci