image: node:latest

variables:
  CI_DEFAULT_ENCODING: 'utf-8'

stages:
  - test

test:
  stage: test
  script:
    - npm run tsc
    - npm run main
    - npm run jest
    - npm run lint --fix
    - npm run format
  before_script:
    - npm i --save-dev
    - npm ci